"""
KAVACHGRID 3.0 — Alert Service
Phase 3 & Phase 5: Alert Ingestion and Management

Handles:
    - Ingesting alerts generated by edge nodes or analytics engines
    - Alert retrieval, filtering, and operator acknowledgement
"""

from datetime import datetime, timezone
from typing import List, Optional
import uuid

from sqlalchemy.orm import Session

from app.db.models import Alert
from app.schemas.alert import AlertCreate
from app.services.device_service import device_service


class AlertService:
    """Service layer for alert creation and management."""

    @staticmethod
    def create_alert(
        db: Session,
        data: AlertCreate,
    ) -> Alert:
        """Create and persist a new alert in the database."""
        if data.device_id:
            device_service.ensure_device_exists(db, data.device_id)

        now = datetime.now(timezone.utc)
        alert = Alert(
            id=uuid.uuid4(),
            device_id=data.device_id,
            alert_type=data.alert_type,
            severity=data.severity,
            title=data.title,
            message=data.message,
            details=data.details,
            acknowledged=False,
            created_at=now,
        )

        db.add(alert)
        db.commit()
        db.refresh(alert)
        return alert

    @staticmethod
    def get_active_alerts(
        db: Session,
        limit: int = 50,
        unacknowledged_only: bool = False,
    ) -> List[Alert]:
        """Fetch latest alerts ordered by creation time descending."""
        query = db.query(Alert)
        if unacknowledged_only:
            query = query.filter(Alert.acknowledged.is_(False))
        return query.order_by(Alert.created_at.desc()).limit(limit).all()

    @staticmethod
    def acknowledge_alert(
        db: Session,
        alert_id: uuid.UUID,
        user_id: Optional[uuid.UUID] = None,
    ) -> Optional[Alert]:
        """Mark an alert as acknowledged by an operator."""
        alert = db.query(Alert).filter(Alert.id == alert_id).first()
        if not alert:
            return None

        alert.acknowledged = True
        alert.acknowledged_by = user_id
        alert.acknowledged_at = datetime.now(timezone.utc)

        db.commit()
        db.refresh(alert)
        return alert


alert_service = AlertService()
