"""
KAVACHGRID 3.0 — Alert Service
Phase 3 & Phase 5: Alert Ingestion and Management

Handles:
    - Ingesting alerts generated by edge nodes or analytics engines
    - Alert retrieval, filtering, and operator acknowledgement
    - Alert summary statistics for dashboard
"""

from datetime import datetime, timezone
from typing import Dict, List, Optional
import uuid

from sqlalchemy import func
from sqlalchemy.orm import Session

from app.db.models import Alert
from app.schemas.alert import AlertCreate, AlertSummary
from app.services.device_service import device_service


class AlertService:
    """Service layer for alert creation and management."""

    @staticmethod
    def create_alert(
        db: Session,
        data: AlertCreate,
    ) -> Alert:
        """Create and persist a new alert in the database."""
        if data.device_id:
            device_service.ensure_device_exists(db, data.device_id)

        now = datetime.now(timezone.utc)
        alert = Alert(
            id=uuid.uuid4(),
            device_id=data.device_id,
            alert_type=data.alert_type,
            severity=data.severity,
            title=data.title,
            message=data.message,
            details=data.details,
            acknowledged=False,
            created_at=now,
        )

        db.add(alert)
        db.commit()
        db.refresh(alert)
        return alert

    @staticmethod
    def get_alert_by_id(
        db: Session,
        alert_id: uuid.UUID,
    ) -> Optional[Alert]:
        """Fetch a single alert by its primary key UUID."""
        return db.query(Alert).filter(Alert.id == alert_id).first()

    @staticmethod
    def get_active_alerts(
        db: Session,
        limit: int = 50,
        unacknowledged_only: bool = False,
        severity: Optional[str] = None,
        alert_type: Optional[str] = None,
        device_id: Optional[str] = None,
    ) -> List[Alert]:
        """Fetch latest alerts with optional filters."""
        query = db.query(Alert)
        if unacknowledged_only:
            query = query.filter(Alert.acknowledged.is_(False))
        if severity:
            query = query.filter(Alert.severity == severity)
        if alert_type:
            query = query.filter(Alert.alert_type == alert_type)
        if device_id:
            query = query.filter(Alert.device_id == device_id)
        return query.order_by(Alert.created_at.desc()).limit(limit).all()

    @staticmethod
    def get_alerts_by_device(
        db: Session,
        device_id: str,
        limit: int = 50,
    ) -> List[Alert]:
        """Fetch alerts for a specific device."""
        return (
            db.query(Alert)
            .filter(Alert.device_id == device_id)
            .order_by(Alert.created_at.desc())
            .limit(limit)
            .all()
        )

    @staticmethod
    def acknowledge_alert(
        db: Session,
        alert_id: uuid.UUID,
        user_id: Optional[uuid.UUID] = None,
    ) -> Optional[Alert]:
        """Mark an alert as acknowledged by an operator."""
        alert = db.query(Alert).filter(Alert.id == alert_id).first()
        if not alert:
            return None

        alert.acknowledged = True
        alert.acknowledged_by = user_id
        alert.acknowledged_at = datetime.now(timezone.utc)

        db.commit()
        db.refresh(alert)
        return alert

    @staticmethod
    def get_alert_summary(db: Session) -> AlertSummary:
        """
        Compute dashboard alert summary with counts by severity and type.
        """
        total = db.query(func.count(Alert.id)).scalar() or 0
        unacknowledged = (
            db.query(func.count(Alert.id))
            .filter(Alert.acknowledged.is_(False))
            .scalar()
            or 0
        )

        # Count by severity
        severity_rows = (
            db.query(Alert.severity, func.count(Alert.id))
            .group_by(Alert.severity)
            .all()
        )
        by_severity: Dict[str, int] = {row[0]: row[1] for row in severity_rows}

        # Count by type
        type_rows = (
            db.query(Alert.alert_type, func.count(Alert.id))
            .group_by(Alert.alert_type)
            .all()
        )
        by_type: Dict[str, int] = {row[0]: row[1] for row in type_rows}

        return AlertSummary(
            total=total,
            unacknowledged=unacknowledged,
            by_severity=by_severity,
            by_type=by_type,
        )


alert_service = AlertService()
